name: Feature Request
description: Submit a request for a new feature for PyBuster.
assignees: ["Schousboe"]
labels: ["feature-request"]
title: "[FEATURE-REQUEST]: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for filling this feature-request template so we can get some new features! :)

  - type: textarea
    id: feature-description
    attributes:
      label: "Describe the exact feature you want"
      description: "Explain the feature and how it would make PyBuster better"
    validations:
      required: true

  - type: textarea
    id: user_impact
    attributes:
      label: "Describe the impact that this has on users"
      description: "How does this feature affect users?"
    validations:
      required: true

  - type: checkboxes
    id: business_impact
    attributes:
      label: "Select the technical impact"
      description: "Which of these does the request help with?"
      options:
        - label: Find more vulnerabilities
        - label: Reduce false positives
        - label: Speed up scanning
        - label: Add support for new protocols / endpoints
        - label: Improve reporting / log accuracy
        - label: Enhance integrations with other tools
        - label: Improve stability / avoid crashes
        - label: Reduce manual effort
        - label: Other
    validations:
      required: true

  - type: checkboxes
    id: cost_of_not_doing
    attributes:
      label: "Cost of not doing this"
      options:
        - label: Missed vulnerabilities
        - label: Slower recon / scans
        - label: Higher false positives / false negatives
        - label: Manual effort required
        - label: Users switch to other tools
        - label: Falling behind modern targets
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: "How urgent is this request?"
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true    

  - type: textarea
    id: solution_ideas
    attributes:
      label: "Describe any implementation ideas"
      description: "If you have thoughts on how to build this, add them here."

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other relevant info for the feature.

  - type: input
    id: contact
    attributes:
      label: Contact details (optional)
      placeholder: "email@example.com"
      description: "Optional — helps us if we need follow-up questions"

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT).
      options:
        - label: I agree to follow this project's Code of Conduct
    validations:
      required: true
