style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Schousboe/PyBuster
options:
  commits:
     filters:
       Type:
         - feat
         - fix
         - perf
         - refactor
         - ci/cd
         - test
         - docs
  commit_groups:
     title_maps:
       feat: Features
       fix: Bug Fixes
       perf: Performance Improvements
       refactor: Code Refactoring
       ci/cd: Continous integration/Cointinous Delivery
       test: Tests
       docs: Documentation
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE