style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Schousboe/PyBuster
options:
  commits:
    filters:
      exclude:
        - "update CHANGELOG.md [skip ci]"
      Type:
        - feat
        - fix
        - chore
        - perf
        - refactor
        - ci/cd
        - test
        - docs

  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE