name: Update CHANGELOG

# Trigger on new Git tags
on:
  push:
   branches:
    main
    

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0     
          fetch-tags: true   


      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install git-chglog
        run: go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest

      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Generate CHANGELOG
        run: git-chglog -o CHANGELOG.md

      # Step 6: Commit and push changes
      - name: Commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md [skip ci]" || echo "No changes to commit"
          git push
